---

- name: Sample playbook
  hosts: all
  
  tasks:
  - name: print hello world
    command: "ping -c3 yahoo.com"
    register: IP_INFO

  - name: print IP info
    debug:
      msg: "{{ IP_INFO }}"
